# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/888f98d8-4be8-4630-8c7c-36ccc0b66aeb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6DF4-83E1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
 fileSystems."/mnt/ronald" = {
   device = "//10.10.10.3/ronald";
   fsType = "cifs";
   options = [ "credentials=/root/.ronald" "x-systemd.automount" "auto" "uid=1000" "gid=100" "file_mode=0700" "dir_mode=0700" ];
 };

 fileSystems."/mnt/debbie" = {
   device = "//10.10.10.3/debbie";
   fsType = "cifs";
   options = [ "credentials=/root/.debbie" "x-systemd.automount" "auto" "uid=1000" "gid=100" "file_mode=0700" "dir_mode=0700" ];
 };

 fileSystems."/mnt/ps2" = {
   device = "//10.10.10.3/ps2";
   fsType = "cifs";
   options = [ "credentials=/root/.ronald" "x-systemd.automount" "auto" "uid=1000" "gid=100" "file_mode=0700" "dir_mode=0700" ];
 };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
